### ISSUE TITLE
FB_Tree_Map.Remove() balancing 

### ISSUE THREAD

**Issue by freiurs** [fisothemes/TwinCat-Dynamic-Collections#3]
Hi @fisothemes 
When removing an element from a FB_Tree_Map the map is balanced. I suspect the balancing here is not correct. Because the node is deleted first and then the balancing is done with this deleted node, which memory is not anymore in use.
As you can see in the printscreen, the memory area of the pTemp node which was removed before is now already in use again by other dynamic objects (in my program). This can lead to exceptions.
I'm not sure, but shouldn't balancing be done from the previsous node (pTemp^.pParent) in this case?
Which have to be saved before removing the pTemp.

e.g.
pPrevious := pTmp^.pParent;	
THIS^.Remove_Node(pTmp);
THIS^.Balance(pPrevious);

![FB_Tree_Map balancing](https://github.com/fisothemes/TwinCat-Dynamic-Collections/assets/57216920/a334daf1-020c-4080-b444-544474bc4dfd)

**Comment by fisothemes** [comment]
Hi @freiurs thanks for bringing this to my attention, very detailed and helpful issue. I'll try to fix it as soon as I can, it might not be this week since I'll be away on Holiday.

**Comment by freiurs** [comment]
Hi @fisothemes 
No stress, have a nice Holiday!

**Comment by fisothemes** [comment]
Fixed on [pre-release 1.0.5,25](https://github.com/fisothemes/TwinCat-Dynamic-Collections/releases/tag/v1.0.5.25)
