### ISSUE TITLE
Idea: add this library to Twinpack

### ISSUE THREAD

**Issue by rruiter87** [fisothemes/TwinCat-Dynamic-Collections#5]
Twinpack is a third party package manager for TwinCAT and is convenient to distribute your libraries. See https://github.com/Zeugwerk/Twinpack-Registry and https://github.com/Zeugwerk/Twinpack

**Comment by fisothemes** [comment]
Thanks again for the suggestion and the helpful links, I keep forgetting, I have submitted a pull request so it's automatic in the future.
The current version is already on Twinpack now.
